/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [4.73KB] > /mnt/c/Users/david/3DModels/Portfolio_tut/ElfScythe/scene-transformed.glb [292.85KB] (-6091%)
Author: Mostafa Rashad (https://sketchfab.com/m-m-rashad)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/darksiders-scythe-of-death-f9f1f025112648fb9557cb789e3d0074
Title: Darksiders: Scythe of Death
*/
"use client"
import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_3.geometry} material={materials.scythe_mat} position={[-3.554, -4.905, 0.361]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
