/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [14.6KB] > /mnt/c/Users/david/3DModels/Portfolio_tut/WizardHat/scene-transformed.glb [505.57KB] (-3363%)
Author: Paulina (https://sketchfab.com/Byakko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wizards-hat-68a9fb2dbd8442a5bacf9c0141320308
Title: Wizard's hat
*/
"use client"
import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function WizardHat(props) {
  const { nodes, materials } = useGLTF('/models/wizardHat-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert21} />
    </group>
  )
}

useGLTF.preload('/models/wizardHat-transformed.glb')
