/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [14.6KB] > /mnt/c/Users/david/3DModels/Portfolio_tut/WizardHat/scene-transformed.glb [505.57KB] (-3363%)
Author: Paulina (https://sketchfab.com/Byakko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wizards-hat-68a9fb2dbd8442a5bacf9c0141320308
Title: Wizard's hat
*/
"use client"
import React, { useRef } from 'react'
import { Center, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function WizardHat(props) {
  const { nodes, materials } = useGLTF('/models/wizardHat-transformed.glb')

  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.008

  })
  return (
    <group 
    ref={modelRef}
    {...props} dispose={null}
      position={[-0.1, 0.5, -1]}
      scale={[2.2, 2.2, 2]}
      rotation={[0.3, 4.2, 0.2]}>
      <Center><mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert21} /></Center>
    </group>
  )
}

useGLTF.preload('/models/wizardHat-transformed.glb')
